docker: Add DOCKER_FROM arg
The dockerfile for each architecture is the same except for the 'FROM' image.
Add a new Dockerfile argument DOCKER_FROM that allows for a commom dockerfile.
If the docker version is older than 17.05 generate a docker file from
the common one.

Signed-off-by: Geoff Levand <geoff@infradead.org>
Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

diff --git a/docker/builder-include b/docker/builder-include
--- a/docker/builder-include
+++ b/docker/builder-include
@@ -19,6 +19,19 @@ arch_tag() {
 	esac
 }
 
+docker_from() {
+	local a="$(arch)"
+
+	case "${a}" in
+		amd64) echo "ubuntu:17.10" ;;
+		arm64) echo "arm64v8/ubuntu:17.10" ;;
+		*)
+			echo "${name}: ERROR: Unknown arch ${a}" >&2
+			exit 1
+		;;
+	esac
+}
+
 run_cmd () {
 	local cmd="${*}"
 
